### ISSUE TITLE
I can't find what I'm looking for: plugins/opensource/hr.md

### ISSUE THREAD

**Issue by leoc8697** [tinymce/tinymce-docs#2017]
I need to be able to css style that horizontal line. Thanks

**Comment by tylerkelly13** [comment]
Hi @leoc8697 

The default styles on horizontal rules in TinyMCE are:
```css
hr {
  border-color: #ccc;
  border-style: solid;
  border-width: 1px 0 0 0;
}
```

They can also be found in the tinymce-dist repository: https://github.com/tinymce/tinymce-dist/blob/dbf8c9ab481e11b660a957257c73f55e2af83b20/skins/content/document/content.css#L58

Tyler
